#!/bin/sh

media-ctl -d /dev/media5 --set-v4l '"80160000.Dahua_Fifo_To_Axis":0 [fmt:UYVY8_1X16/640x512]'
gst-launch-1.0 -v v4l2src io-mode=4 device=/dev/video2 ! video/x-raw,format=NV16,width=640,height=512 ! tee name=t \
t. ! queue ! omxh264enc target-bitrate=4000 ! rtph264pay ! udpsink host=10.233.1.67 port=5002 \
t. ! queue ! fpsdisplaysink video-sink=fakesink sync=false
