#!/bin/sh

media-ctl -d /dev/media0 --set-v4l '"80180000.Econ_Fifo_To_Axis":0 [fmt:UYVY8_1X16/1920x1080]'
gst-launch-1.0 -v v4l2src device=/dev/video4 io-mode=4 ! video/x-raw,format=UYVY,width=1920,height=1080,framerate=30/1 ! tee name=t \
t. ! queue ! fpsdisplaysink video-sink=fakesink sync=false \
t. ! queue ! rtpvrawpay ! udpsink host=10.233.1.222 port=5005
